### ISSUE TITLE
lidarr_search-missing-tracks.sh: cut: invalid decreasing range

### ISSUE THREAD

**Issue by markbsigler** [ultimate-pms/ultimate-media-server-core#1]
Ubuntu 18.04.1

Processing results:
|############################################################| 120 % The Alternate Tango in the Night...cut: invalid decreasing range
Try 'cut --help' for more information.
cut: invalid decreasing range
...

**Comment by david-nedved** [comment]
@markbsigler - Could you please post your `GENRES_TO_ADD=()` array from the top of the `lidarr_search-missing-tracks.sh` file? 

Cheers,

**Comment by markbsigler** [comment]
That array is in your other Lidarr script.

--
Mark


On Aug 26, 2018 at 19:56, david-nedved <notifications@github.com> wrote:


@markbsigler <https://github.com/markbsigler> - Could you please post your
GENRES_TO_ADD=() array from the top of the lidarr_search-missing-tracks.sh
file?

Cheers,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ultimate-pms/ultimate-plex-setup/issues/1#issuecomment-416082427>,
or mute the thread

**Comment by ned-kelly** [comment]
@markbsigler Can you please run `cut --version` - Can't seem to reproduce this issue with `cut (GNU coreutils) 8.24`

Thanks.

**Comment by markbsigler** [comment]
> @markbsigler Can you please run `cut --version` - Can't seem to reproduce this issue with `cut (GNU coreutils) 8.24`
> 
> Thanks.

$ cut --version -
cut (GNU coreutils) 8.28C
$ uname -a
Linux Ohana 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Jerrk** [comment]
I believe it has to do with the URL base in lidarr.
i cleared the URL base and then ran the script with no errors.
i then edited the script and added a variable for the URL base ~~and now it works no issue.~~

EDIT: after reaching 100% it started throwing the error at me again.
Unraid 6.9.1
```
:~# cut --version 
cut (GNU coreutils) 8.32
```
```
Script location: /tmp/user.scripts/tmpScripts/Lidarr Search Missing Tracks/script
Note that closing this window will abort the execution of this script
++ Lidarr Music Search Trigger(er) ++
------------------------------


Querying API for missing tracks - please be patient...

Processing results:
[K|################################################# | 99 % 1998‐12‐10: Amnesty International Concert, Paris, France...cut: invalid decreasing range
Try 'cut --help' for more information.
cut: invalid decreasing range
Try 'cut --help' for more information.
cut: invalid decreasing range
Try 'cut --help' for more information.
cut: invalid decreasing range
```
