### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by vaheed** [ultimate-pms/ultimate-media-server-core#6]
ERROR: pull access denied for jkaberg/tvhproxy, repository does not exist or may require 'docker login'

ERROR: Service 'plexconnect' failed to build: Get https://registry-1.docker.io/v2/varju/plexconnect/manifests/latest: dial tcp: lookup registry-1.docker.io: No address 

do you have any idea why !!?

**Comment by ned-kelly** [comment]
> ERROR: Service 'plexconnect' failed to build: Get https://registry-1.docker.io/v2/varju/plexconnect/manifests/latest: dial tcp: lookup registry-1.docker.io: No address

What version of docker (and docker compose) are you running? - Can you pls make sure you're running the latest version of `docker-ce` as some of the older versions of docker can't connect to the registry.
